name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow for bitter_de
        run: |
          curl -XPOST -u "bitterdev:${{secrets.PRIVATE_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/bitterdev/bitter_de/dispatches --data '{"event_type": "build_application"}'
